# Generated by Django 5.1.3 on 2024-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('FatherName', models.CharField(blank=True, max_length=64, null=True)),
                ('GuardianName', models.CharField(blank=True, max_length=64, null=True)),
                ('MotherName', models.CharField(max_length=64)),
                ('DateofBirth', models.DateField()),
                ('class1', models.CharField(max_length=64)),
                ('SubjectName', models.CharField(max_length=256)),
                ('School', models.CharField(max_length=256)),
                ('Board', models.CharField(max_length=64)),
                ('Address', models.TextField()),
                ('ContactNo', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('DateofJoining', models.DateField()),
                ('AgreeToDeclaration', models.BooleanField(default=False)),
            ],
        ),
    ]
